### ISSUE TITLE
Unable to open app after latest update

### ISSUE THREAD

**Issue by python4lyfe** [brandonp2412/Flexify#97] opened 2024-07-31 09:58 UTC
**Describe the bug**

**To Reproduce**
1. Launch app

**Expected behavior**
App opens for use

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8
 - OS: GrapheneOS

**Additional context**
Crash report

```
type: crash
osVersion: google/shiba/shiba:14/AP2A.240705.005/2024072800:user/release-keys
package: com.presley.flexify:1743
process: com.presley.flexify
processUptime: 137 + 205 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.presley.flexify/com.presley.flexify.MainActivity}: android.database.sqlite.SQLiteException: no such column: backup_path (code 1 SQLITE_ERROR): , while compiling: SELECT backup_path, automatic_backups FROM settings
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4004)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.database.sqlite.SQLiteException: no such column: backup_path (code 1 SQLITE_ERROR): , while compiling: SELECT backup_path, automatic_backups FROM settings
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.-$$Nest$smnativePrepareStatement(Unknown Source:0)
	at android.database.sqlite.SQLiteConnection$PreparedStatementCache.createStatement(SQLiteConnection.java:1562)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatementLI(SQLiteConnection.java:1098)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1126)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:686)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:614)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1818)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1750)
	at b2.l.a(Unknown Source:79)
	at com.presley.flexify.MainActivity.onCreate(Unknown Source:12)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	... 15 more
```

**Comment by brandonp2412** [comment] 2024-07-31 10:26
Duplicate of https://github.com/brandonp2412/Flexify/issues/95

**Closed by brandonp2412** 2024-07-31 10:26 UTC
