### ISSUE TITLE
Add notes for exercise

### ISSUE THREAD

**Issue by samuelmurschall** [brandonp2412/Flexify#113] opened 2024-08-18 00:43 UTC
**Is your feature request related to a problem? Please describe.**No
**Describe the solution you'd like**Add the option "Notes" in the menu besides Settings and Graphs as you press and hold on an exercise. Users could also have the option to select how he would like his notes to be shown as he creates them. The notes could be shown as a text, an ordered or unordered list.

**Comment by brandonp2412** [comment] 2024-08-18 01:08
Duplicate of #70

**Closed by brandonp2412** 2024-08-18 01:08 UTC
