### ISSUE TITLE
App keeps stopping on opening

### ISSUE THREAD

**Issue by samuelmurschall** [brandonp2412/Flexify#94] opened 2024-07-28 16:10 UTC
The issue appeared after installing the latest version 
[Error in Flexify 924fded69ee5.txt](https://github.com/user-attachments/files/16404422/Error.in.Flexify.924fded69ee5.txt)

**Comment by tomas-samot** [comment] 2024-07-28 16:35
I had the same issue. I fixed the issue by installing the latest version.

**Comment by brandonp2412** [comment] 2024-07-28 23:11
@samuelmurschall which version is this occurring on?

**Comment by samuelmurschall** [comment] 2024-07-28 23:39
Version 1.1.65

**Comment by brandonp2412** [comment] 2024-07-28 23:48
Duplicate of https://github.com/brandonp2412/Flexify/issues/91

**Closed by brandonp2412** 2024-07-28 23:48 UTC

**Comment by samuelmurschall** [comment] 2024-07-30 15:04
Sorry, I didn't saw the closed issue. Can you give me a date, when the new Version will be available on F-Droid?
