### ISSUE TITLE
App no longer launches since update 1.1.42

### ISSUE THREAD

**Issue by amohacker** [brandonp2412/Flexify#75] opened 2024-07-15 11:15 UTC
I am running Android 14 and since updating to version 1.1.42 the app no longer starts. It gets up to showing the logo in full screen and no further.

**Comment by brandonp2412** [comment] 2024-07-15 11:33
What is your current app version and please attach relevant ADB logs

**Comment by amohacker** [comment] 2024-07-15 13:58
I am currently on the latest version available on F-Droid, although I have beta versions disabled.

**Comment by brandonp2412** [comment] 2024-07-15 21:20
You can see the latest versions here https://github.com/brandonp2412/Flexify/releases/latest this ticket is almost certainly a duplicate of https://github.com/brandonp2412/Flexify/issues/66 but if you like you can paste adb logs and I'll give them a look

**Comment by amohacker** [comment] 2024-07-15 21:40
After trying the version listed there the issue disappeared so that does seem to have been the issue. If you maintain the image on F-Droid I recommend uploading this new to there since others are probably having the same problem there.

**Closed** 2024-07-15 21:40 UTC

**Comment by brandonp2412** [comment] 2024-07-15 21:50
> After trying the version listed there the issue disappeared so that does seem to have been the issue. If you maintain the image on F-Droid I recommend uploading this new to there since others are probably having the same problem there.

I can't control when f-droid accepts my updates but to be honest they accept them faster than Google play hahahahahah
